# Generated by Django 2.0.6 on 2018-08-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='Latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='retailer',
            name='Longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20),
        ),
    ]
