# Generated by Django 2.0.6 on 2018-08-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0002_auto_20180807_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailer',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='retailer',
            old_name='Longitude',
            new_name='longitude',
        ),
    ]
