# Generated by Django 2.0.3 on 2018-05-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='exp_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
