# Generated by Django 2.0.3 on 2018-05-20 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20180520_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(blank=True, max_length=120, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('amount_refunded', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=120, null=True)),
                ('paid', models.CharField(blank=True, max_length=120, null=True)),
                ('refunded', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.CharField(blank=True, max_length=20, null=True)),
                ('failure_message', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')),
            ],
        ),
    ]
