# Generated by Django 2.0.3 on 2018-05-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='Default',
            field=models.BooleanField(default=True),
        ),
    ]
