# Generated by Django 2.0.3 on 2018-05-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_card_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='Default',
            new_name='default',
        ),
    ]
