# Generated by Django 2.0.3 on 2018-05-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20180520_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='source',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
