# Generated by Django 2.0.3 on 2018-05-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_card_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='outcome',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charge',
            name='failure_message',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
    ]
