# Generated by Django 2.0.3 on 2018-05-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20180520_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='failure_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='outcome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
