# Generated by Django 2.0.2 on 2018-05-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
