# Generated by Django 2.0.6 on 2018-07-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='area',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=11),
        ),
        migrations.AlterField(
            model_name='entry',
            name='packs',
            field=models.IntegerField(default=100),
        ),
    ]
