# Generated by Django 2.0.2 on 2018-06-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailchimp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailchimp',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(),
        ),
    ]
