# Generated by Django 2.0.2 on 2018-06-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailchimp', '0002_mailchimp_mailchimp_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailchimp',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(default=True),
        ),
    ]
