# Generated by Django 2.0.2 on 2018-06-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailchimp', '0003_auto_20180608_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailchimp',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(),
        ),
    ]
