# Generated by Django 2.0.2 on 2018-05-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='bruce', max_length=30, verbose_name='user name'),
            preserve_default=False,
        ),
    ]
