# Generated by Django 2.0.2 on 2018-04-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
    ]
