# Generated by Django 2.0.1 on 2018-04-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180411_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='billingprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='BillingProfile',
        ),
    ]
