# Generated by Django 2.0.2 on 2018-05-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='user name'),
        ),
    ]
