# Generated by Django 2.0.2 on 2018-04-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180416_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestemail',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='guestemail',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
