# Generated by Django 2.0.2 on 2018-04-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180417_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestemail',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='guestemail',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
