# Generated by Django 2.0.2 on 2018-04-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180417_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billingprofile',
            new_name='billing_profile',
        ),
    ]
