# Generated by Django 2.0.6 on 2018-07-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated', '-timestamp']},
        ),
    ]
