# Generated by Django 2.0.6 on 2018-08-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=59, max_digits=11),
        ),
    ]
